"""add slug to categories

Revision ID: a5c0c54d7934
Revises: fb50c3b66446
Create Date: 2026-03-12 16:09:32.946186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c0c54d7934'
down_revision: Union[str, Sequence[str], None] = 'fb50c3b66446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'categories', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
